const MAX_HOSTNAMES = 20;
const form = document.getElementById('suppressionForm');
const hostnamesInput = document.getElementById('hostnames');
const hostnameCount = document.getElementById('hostnameCount');
const validationMessage = document.getElementById('validationMessage');
const submitButton = document.getElementById('submitButton');
const resultArea = document.getElementById('resultArea');

function esc(v){return String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;')}
function parseHostnames(v){return [...new Set(v.split(/[\n,;]+/).map(x=>x.trim().toUpperCase()).filter(Boolean))]}
function updateCount(){hostnameCount.textContent=`${parseHostnames(hostnamesInput.value).length} / ${MAX_HOSTNAMES}`}
function successTable(items){if(!items?.length)return'';return `<h3>Successful VMs</h3><div class="table-wrap"><table><thead><tr><th>Hostname</th><th>Azure VM</th><th>Subscription</th><th>Resource group</th><th>Status</th><th>Rule</th></tr></thead><tbody>${items.map(i=>`<tr><td>${esc(i.hostname)}</td><td>${esc(i.vmName)}</td><td>${esc(i.subscriptionName)}</td><td>${esc(i.resourceGroup)}</td><td><span class="badge badge-ok">${esc(i.status||'Created')}</span></td><td>${esc(i.ruleName)}</td></tr>`).join('')}</tbody></table></div>`}
function failureTable(items){if(!items?.length)return'';return `<h3>Failed VMs</h3><div class="table-wrap"><table><thead><tr><th>Hostname</th><th>Status</th><th>Stage</th><th>Reason</th></tr></thead><tbody>${items.map(i=>`<tr><td>${esc(i.hostname||i.hostnameSubmitted)}</td><td><span class="badge badge-fail">${esc(i.status||'Failed')}</span></td><td>${esc(i.failureStage)}</td><td>${esc(i.message||i.details?.message||'Automation failed')}</td></tr>`).join('')}</tbody></table></div>`}
function showResult(r,httpStatus){let cls='failure',title='Request failed';if(r.status==='Created'){cls='success';title='All suppression rules were created'}else if(r.status==='PartiallyCreated'){cls='warning';title='Request partially completed'}resultArea.hidden=false;resultArea.innerHTML=`<div class="banner ${cls}"><h2>${esc(title)}</h2><p><strong>Request ID:</strong> ${esc(r.requestId||'Not available')}</p><p>${esc(r.message||`HTTP status ${httpStatus}`)}</p></div><div class="summary"><div><strong>${esc(r.submittedCount??0)}</strong>Submitted</div><div><strong>${esc(r.uniqueCount??0)}</strong>Unique</div><div><strong>${esc(r.successCount??0)}</strong>Successful</div><div><strong>${esc(r.failureCount??0)}</strong>Failed</div></div>${successTable(r.successfulResults)}${failureTable(r.failedResults)}`;resultArea.scrollIntoView({behavior:'smooth'})}

hostnamesInput.addEventListener('input',updateCount);
document.getElementById('clearButton').addEventListener('click',()=>{form.reset();validationMessage.textContent='';resultArea.hidden=true;resultArea.innerHTML='';updateCount()});
form.addEventListener('submit',async e=>{e.preventDefault();validationMessage.textContent='';const p={requesterName:document.getElementById('requesterName').value.trim(),requesterEmail:document.getElementById('requesterEmail').value.trim(),employeeId:document.getElementById('employeeId').value.trim(),portalAccessCode:document.getElementById('portalAccessCode').value,hostnames:parseHostnames(hostnamesInput.value),startDateTime:document.getElementById('startDateTime').value,endDateTime:document.getElementById('endDateTime').value,timeZone:document.getElementById('timeZone').value,changeNumber:document.getElementById('changeNumber').value.trim(),reason:document.getElementById('reason').value.trim(),environment:document.getElementById('environment').value};if(!p.requesterName||!p.requesterEmail||!p.employeeId||!p.portalAccessCode){validationMessage.textContent='Complete all requester fields.';return}if(p.hostnames.length<1||p.hostnames.length>MAX_HOSTNAMES){validationMessage.textContent='Provide 1 to 20 unique hostnames.';return}if(!p.startDateTime||!p.endDateTime||!p.timeZone||!p.changeNumber||!p.reason){validationMessage.textContent='Complete all suppression fields.';return}if(new Date(p.endDateTime)<=new Date(p.startDateTime)){validationMessage.textContent='End time must be later than start time.';return}submitButton.disabled=true;submitButton.textContent='Processing VMs...';try{const res=await fetch('/api/submitSuppression',{method:'POST',headers:{'Content-Type':'application/json','Accept':'application/json'},body:JSON.stringify(p)});const text=await res.text();let body;try{body=text?JSON.parse(text):{}}catch{body={status:'Failed',message:text||'Invalid API response'}}showResult(body,res.status)}catch(err){showResult({status:'Failed',message:`Request failed: ${err.message}`},0)}finally{submitButton.disabled=false;submitButton.textContent='Submit suppression request'}});
updateCount();
